version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
