services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    container_name: pre-alms-backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      APP_ENV: ${APP_ENV}
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - alms-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: production
    container_name: pre-alms-frontend
    env_file:
      - ./.env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: production
      APP_ENV: ${APP_ENV}
      FRONTEND_PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - alms-net

  nginx:
    image: nginx:stable-alpine
    container_name: pre-alms-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      FRONTEND_PORT: ${FRONTEND_PORT}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
    command: /bin/sh -c "envsubst '$$BACKEND_PORT $$FRONTEND_PORT $$NGINX_SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    networks:
      - alms-net

networks:
  alms-net:
    driver: bridge
