services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: ${NODE_ENV} # Pass NODE_ENV as a build argument
    container_name: pre-alms-backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      BACKEND_PORT: ${BACKEND_PORT}
    networks:
      - alms-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NODE_ENV: ${NODE_ENV} # Pass NODE_ENV as a build argument
    container_name: pre-alms-frontend
    env_file:
      - ./.env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NODE_ENV: ${NODE_ENV}
      FRONTEND_PORT: ${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - alms-net

  nginx:
    image: nginx:stable-alpine
    container_name: pre-alms-nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - alms-net

networks:
  alms-net:
    driver: bridge
