service: alms

org: null  # Opt-out of Serverless Dashboard
app: null  # Opt-out of Serverless Dashboard

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DATABASE: ${env:PG_DATABASE}

functions:
  createEntry:
    handler: handler.createEntry
    events:
      - http:
          path: create-entry
          method: post

resources:
  Resources:
    MyPostgresDB:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: my-postgresql-instance
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        Engine: postgres
        MasterUsername: admin
        MasterUserPassword: P@ssw0rd#AWS2024!
        PubliclyAccessible: true
        DBName: alms_dev_db