'use client';

import React from 'react';

interface RichTextDisplayProps {
  content: string;
  className?: string;
}

/**
 * Component to display rich-text HTML content generated by Tiptap editor.
 * Renders formatted tables, lists, headings, and other rich-text elements
 * with proper styling that matches the editor output.
 */
export const RichTextDisplay: React.FC<RichTextDisplayProps> = ({
  content,
  className = '',
}) => {
  if (!content || !content.trim()) {
    return <p className='text-gray-500 italic'>No content to display</p>;
  }

  return (
    <div className={`prose prose-sm max-w-none ${className}`}>
      <div
        className='rich-text-display'
        dangerouslySetInnerHTML={{ __html: content }}
      />

      <style jsx>{`
        :global(.rich-text-display) {
          font-family: inherit;
          line-height: 1.6;
          color: #333;
        }

        :global(.rich-text-display p) {
          margin: 0.5em 0;
          line-height: 1.6;
        }

        :global(.rich-text-display h1) {
          font-size: 2em;
          font-weight: 700;
          margin: 0.67em 0;
          line-height: 1.2;
        }

        :global(.rich-text-display h2) {
          font-size: 1.5em;
          font-weight: 700;
          margin: 0.75em 0;
          line-height: 1.2;
        }

        :global(.rich-text-display h3) {
          font-size: 1.25em;
          font-weight: 700;
          margin: 0.83em 0;
          line-height: 1.2;
        }

        :global(.rich-text-display strong) {
          font-weight: 700;
        }

        :global(.rich-text-display em) {
          font-style: italic;
        }

        :global(.rich-text-display u) {
          text-decoration: underline;
        }

        :global(.rich-text-display table) {
          border-collapse: collapse;
          margin: 1.5em 0;
          width: 100%;
          overflow-x: auto;
          display: block;
        }

        :global(.rich-text-display table td),
        :global(.rich-text-display table th) {
          border: 1px solid #d1d5db;
          padding: 12px;
          text-align: left;
          word-break: break-word;
        }

        :global(.rich-text-display table th) {
          background-color: #f9fafb;
          font-weight: 600;
          color: #1f2937;
        }

        :global(.rich-text-display table tbody tr:nth-child(odd)) {
          background-color: #fafbfc;
        }

        :global(.rich-text-display table tbody tr:hover) {
          background-color: #f3f4f6;
        }

        :global(.rich-text-display ul),
        :global(.rich-text-display ol) {
          margin: 1em 0;
          padding-left: 2em;
        }

        :global(.rich-text-display ul li),
        :global(.rich-text-display ol li) {
          margin: 0.5em 0;
          line-height: 1.6;
        }

        :global(.rich-text-display blockquote) {
          border-left: 4px solid #4b5563;
          margin: 1.5em 0;
          padding-left: 1em;
          color: #4b5563;
          font-style: italic;
        }

        :global(.rich-text-display code) {
          background-color: #f3f4f6;
          padding: 0.2em 0.4em;
          border-radius: 3px;
          font-family: 'Courier New', monospace;
          font-size: 0.9em;
          color: #dc2626;
        }

        :global(.rich-text-display pre) {
          background: #1f2937;
          border-radius: 0.5rem;
          color: #f3f4f6;
          font-family: 'Courier New', monospace;
          margin: 1.5em 0;
          padding: 1em;
          overflow-x: auto;
          line-height: 1.4;
        }

        :global(.rich-text-display pre code) {
          background: none;
          color: inherit;
          padding: 0;
          font-size: 0.9em;
        }

        :global(.rich-text-display hr) {
          border: none;
          border-top: 1px solid #d1d5db;
          margin: 2em 0;
        }

        :global(.rich-text-display a) {
          color: #3b82f6;
          text-decoration: underline;
          cursor: pointer;
        }

        :global(.rich-text-display a:hover) {
          color: #1d4ed8;
        }
      `}</style>
    </div>
  );
};
